apiVersion: v1
kind: Secret
metadata:
  name: chronicle-mysql
  namespace: chronicle
type: Opaque
stringData:
  MYSQL_DATABASE: tessera
  MYSQL_USER: tessera
  MYSQL_PASSWORD: tessera
  MYSQL_ROOT_PASSWORD: tessera-root
