apiVersion: kaniop.rs/v1beta1
kind: KanidmPersonAccount
metadata:
  name: linh
spec:
  kanidmRef:
    name: my-idm
  credentialsTokenTtl: 86400
  personAttributes:
    displayname: Linh Tran
    mail:
      - linh@example.com
---
apiVersion: kaniop.rs/v1beta1
kind: KanidmServiceAccount
metadata:
  name: seal
spec:
  kanidmRef:
    name: my-idm
  generateCredentials: true
  serviceAccountAttributes:
    displayname: Seal
    entryManagedBy: idm_admin
    mail:
      - seal@example.com
  apiTokens:
    - label: seal-default
      purpose: readonly
      secretName: seal-kanidm-api-token
