#!/usr/bin/env sh
set -eu

STORAGE_NAMESPACE=${STORAGE_NAMESPACE:-storage}
STORAGE_RELEASE=${STORAGE_RELEASE:-rustfs}
STORAGE_SERVICE=${STORAGE_SERVICE:-$STORAGE_RELEASE-svc}
STORAGE_API_PORT=${STORAGE_API_PORT:-9000}
STORAGE_CONSOLE_PORT=${STORAGE_CONSOLE_PORT:-9001}

CHRONICLE_NAMESPACE=${CHRONICLE_NAMESPACE:-chronicle}
CHRONICLE_SERVICE=${CHRONICLE_SERVICE:-chronicle}
CHRONICLE_LOCAL_PORT=${CHRONICLE_LOCAL_PORT:-3000}
CHRONICLE_SERVICE_PORT=${CHRONICLE_SERVICE_PORT:-80}

VAULT_NAMESPACE=${VAULT_NAMESPACE:-vault}
VAULT_SERVICE=${VAULT_SERVICE:-vault}
VAULT_LOCAL_PORT=${VAULT_LOCAL_PORT:-8200}
VAULT_SERVICE_PORT=${VAULT_SERVICE_PORT:-8200}

KEYCLOAK_NAMESPACE=${KEYCLOAK_NAMESPACE:-keycloak}
KEYCLOAK_SERVICE=${KEYCLOAK_SERVICE:-keycloak-service}
KEYCLOAK_LOCAL_PORT=${KEYCLOAK_LOCAL_PORT:-8443}
KEYCLOAK_SERVICE_PORT=${KEYCLOAK_SERVICE_PORT:-8443}
KEYCLOAK_LOCAL_HOST=${KEYCLOAK_LOCAL_HOST:-keycloak-service.keycloak.svc.cluster.local}

pids=""

cleanup() {
  for pid in $pids; do
    kill "$pid" >/dev/null 2>&1 || true
  done
}

trap cleanup INT TERM EXIT

echo "Forwarding storage API:       localhost:$STORAGE_API_PORT -> svc/$STORAGE_SERVICE:9000"
echo "Forwarding storage console:   localhost:$STORAGE_CONSOLE_PORT -> svc/$STORAGE_SERVICE:9001"
kubectl -n "$STORAGE_NAMESPACE" port-forward "svc/$STORAGE_SERVICE" \
  "$STORAGE_API_PORT:9000" \
  "$STORAGE_CONSOLE_PORT:9001" &
pids="$pids $!"

echo "Forwarding chronicle:        localhost:$CHRONICLE_LOCAL_PORT -> svc/$CHRONICLE_SERVICE:$CHRONICLE_SERVICE_PORT"
kubectl -n "$CHRONICLE_NAMESPACE" port-forward "svc/$CHRONICLE_SERVICE" \
  "$CHRONICLE_LOCAL_PORT:$CHRONICLE_SERVICE_PORT" &
pids="$pids $!"

echo "Forwarding vault:            localhost:$VAULT_LOCAL_PORT -> svc/$VAULT_SERVICE:$VAULT_SERVICE_PORT"
kubectl -n "$VAULT_NAMESPACE" port-forward "svc/$VAULT_SERVICE" \
  "$VAULT_LOCAL_PORT:$VAULT_SERVICE_PORT" &
pids="$pids $!"

if ! dscacheutil -q host -a name "$KEYCLOAK_LOCAL_HOST" >/dev/null 2>&1; then
  cat <<EOF
Warning: $KEYCLOAK_LOCAL_HOST does not resolve locally.
Add this to /etc/hosts before using Keycloak:
  127.0.0.1 $KEYCLOAK_LOCAL_HOST

EOF
fi

echo "Forwarding keycloak:         $KEYCLOAK_LOCAL_HOST:$KEYCLOAK_LOCAL_PORT -> svc/$KEYCLOAK_SERVICE:$KEYCLOAK_SERVICE_PORT"
kubectl -n "$KEYCLOAK_NAMESPACE" port-forward "svc/$KEYCLOAK_SERVICE" \
  "$KEYCLOAK_LOCAL_PORT:$KEYCLOAK_SERVICE_PORT" &
pids="$pids $!"

wait
