#!/usr/bin/env sh
set -eu

MIZUKURA_NAMESPACE=${MIZUKURA_NAMESPACE:-mizukura}
MIZUKURA_RELEASE=${MIZUKURA_RELEASE:-rustfs}
MIZUKURA_SERVICE=${MIZUKURA_SERVICE:-$MIZUKURA_RELEASE-svc}
MIZUKURA_API_PORT=${MIZUKURA_API_PORT:-9000}
MIZUKURA_CONSOLE_PORT=${MIZUKURA_CONSOLE_PORT:-9001}

MIZUKAGAMI_NAMESPACE=${MIZUKAGAMI_NAMESPACE:-mizukagami}
MIZUKAGAMI_SERVICE=${MIZUKAGAMI_SERVICE:-mizukagami}
MIZUKAGAMI_LOCAL_PORT=${MIZUKAGAMI_LOCAL_PORT:-3000}
MIZUKAGAMI_SERVICE_PORT=${MIZUKAGAMI_SERVICE_PORT:-80}

VAULT_NAMESPACE=${VAULT_NAMESPACE:-vault}
VAULT_SERVICE=${VAULT_SERVICE:-vault}
VAULT_LOCAL_PORT=${VAULT_LOCAL_PORT:-8200}
VAULT_SERVICE_PORT=${VAULT_SERVICE_PORT:-8200}

KANIDM_NAMESPACE=${KANIDM_NAMESPACE:-default}
KANIDM_SERVICE=${KANIDM_SERVICE:-my-idm}
KANIDM_LOCAL_PORT=${KANIDM_LOCAL_PORT:-8443}
KANIDM_SERVICE_PORT=${KANIDM_SERVICE_PORT:-8443}
KANIDM_LOCAL_HOST=${KANIDM_LOCAL_HOST:-my-idm.localhost}

pids=""

cleanup() {
  for pid in $pids; do
    kill "$pid" >/dev/null 2>&1 || true
  done
}

trap cleanup INT TERM EXIT

echo "Forwarding mizukura API:      localhost:$MIZUKURA_API_PORT -> svc/$MIZUKURA_SERVICE:9000"
echo "Forwarding mizukura console:  localhost:$MIZUKURA_CONSOLE_PORT -> svc/$MIZUKURA_SERVICE:9001"
kubectl -n "$MIZUKURA_NAMESPACE" port-forward "svc/$MIZUKURA_SERVICE" \
  "$MIZUKURA_API_PORT:9000" \
  "$MIZUKURA_CONSOLE_PORT:9001" &
pids="$pids $!"

echo "Forwarding mizukagami:        localhost:$MIZUKAGAMI_LOCAL_PORT -> svc/$MIZUKAGAMI_SERVICE:$MIZUKAGAMI_SERVICE_PORT"
kubectl -n "$MIZUKAGAMI_NAMESPACE" port-forward "svc/$MIZUKAGAMI_SERVICE" \
  "$MIZUKAGAMI_LOCAL_PORT:$MIZUKAGAMI_SERVICE_PORT" &
pids="$pids $!"

echo "Forwarding vault:            localhost:$VAULT_LOCAL_PORT -> svc/$VAULT_SERVICE:$VAULT_SERVICE_PORT"
kubectl -n "$VAULT_NAMESPACE" port-forward "svc/$VAULT_SERVICE" \
  "$VAULT_LOCAL_PORT:$VAULT_SERVICE_PORT" &
pids="$pids $!"

if ! dscacheutil -q host -a name "$KANIDM_LOCAL_HOST" >/dev/null 2>&1; then
  cat <<EOF
Warning: $KANIDM_LOCAL_HOST does not resolve locally.
Add this to /etc/hosts before using Kanidm passkeys:
  127.0.0.1 $KANIDM_LOCAL_HOST

EOF
fi

echo "Forwarding kanidm:           $KANIDM_LOCAL_HOST:$KANIDM_LOCAL_PORT -> svc/$KANIDM_SERVICE:$KANIDM_SERVICE_PORT"
kubectl -n "$KANIDM_NAMESPACE" port-forward "svc/$KANIDM_SERVICE" \
  "$KANIDM_LOCAL_PORT:$KANIDM_SERVICE_PORT" &
pids="$pids $!"

wait
